const styles = `
:root{color-scheme:dark;--ink:#e5ecea;--muted:#8c9a97;--bg:#0b0e0e;--panel:#101414;--line:#293331;--accent:#42d7b4;--action:#ffb000;--danger:#ff6b57}
*{box-sizing:border-box}html{background:var(--bg);color:var(--ink);font-family:ui-monospace,SFMono-Regular,Consolas,monospace}
body{min-height:100vh;margin:0}.skip{position:fixed;top:-5rem}.skip:focus{top:1rem}.mast{height:60px;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:1.5rem;padding:0 max(1rem,calc((100% - 960px)/2));font-size:.72rem;letter-spacing:.1em}.brand{font:bold 1.1rem system-ui;color:var(--action);text-decoration:none}.signal{margin-left:auto;color:var(--accent)}
main{width:min(960px,calc(100% - 2rem));min-height:calc(100vh - 120px);margin:auto;border-inline:1px solid var(--line)}.owner-nav{display:flex;border-bottom:1px solid var(--line)}.owner-nav a{padding:1rem 1.25rem;color:var(--muted);text-decoration:none;border-bottom:2px solid transparent}.owner-nav a[aria-current=page]{color:var(--ink);border-color:var(--action)}
section,.policy{padding:clamp(2rem,6vw,4rem)}.task{width:min(100%,720px);margin:auto}.eyebrow,label,dt{font-size:.7rem;letter-spacing:.11em;text-transform:uppercase;color:var(--muted)}h1{margin:.25rem 0;font:700 clamp(2rem,5vw,3.25rem)/1.05 system-ui,sans-serif;letter-spacing:-.035em}.lede{margin:1rem 0 2rem;color:var(--muted);line-height:1.65}
form{display:grid;gap:1.1rem}textarea,input,select{width:100%;border:1px solid var(--line);border-radius:3px;background:#080a0a;color:var(--ink);font:inherit;padding:.9rem}textarea{min-height:13rem;resize:vertical}.button{width:max-content;border:1px solid var(--action);border-radius:3px;background:var(--action);color:#090b0b;font:bold .75rem ui-monospace;padding:.9rem 1.1rem;text-transform:uppercase;cursor:pointer}.button:disabled{opacity:.55}.quiet{background:transparent;color:var(--action)}.danger{background:var(--danger);border-color:var(--danger)}
.check-row,.acknowledgment{display:grid;grid-template-columns:auto 1fr;gap:.7rem;align-items:start;color:var(--ink);font-size:.78rem;line-height:1.5;letter-spacing:0;text-transform:none}.check-row input,.acknowledgment input{width:1rem;height:1rem;margin:.15rem 0 0;accent-color:var(--action)}.subpanel,.result,.summary,.detail-card,.notice{border:1px solid var(--line);border-radius:3px;background:var(--panel);padding:1.15rem}.subpanel{display:grid;gap:.75rem}.result{margin-top:1.5rem;border-color:var(--accent)}.copy{display:flex}.fine-print,.message{color:var(--muted);font-size:.78rem;line-height:1.55}.message{min-height:1.25rem}.message[data-error=true]{color:var(--danger)}
.link-list{display:grid;gap:.65rem;margin-top:1.25rem}.link-card{display:grid;grid-template-columns:1fr auto;gap:1rem;border:1px solid var(--line);border-radius:3px;padding:1rem;color:var(--ink);text-decoration:none}.link-card:hover{border-color:var(--accent)}.link-card small,.detail-card dd{color:var(--muted)}.status{color:var(--accent);font-size:.7rem;text-transform:uppercase;text-align:right}.status.finished{color:var(--muted)}dl{margin:0}dl div{display:flex;justify-content:space-between;gap:1rem;padding:.9rem 0;border-bottom:1px solid var(--line)}dd{margin:0;text-align:right}.empty{color:var(--muted);padding:1rem}.notice{margin-top:1.25rem;border-color:var(--action)}a{color:var(--accent)}
.home-actions{display:flex;gap:.75rem;flex-wrap:wrap}.legal-links{display:flex;gap:1rem}footer{min-height:60px;border-top:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;gap:1rem;padding:1rem max(1rem,calc((100% - 960px)/2));color:var(--muted);font-size:.68rem}[hidden]{display:none!important}
@media(max-width:640px){.signal{display:none}.mast{padding:0 1rem}.copy{display:block}.copy .button{margin-top:.5rem}.link-card{grid-template-columns:1fr}.status{text-align:left}footer{align-items:flex-start;flex-direction:column}.legal-links{flex-wrap:wrap}}
`;

const footer = `<footer><span>Browser encrypted</span><nav class="legal-links"><a href="/safety">Safety</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a></nav><span>No app analytics</span></footer>`;
const nav = (active: "create" | "links") => `<nav class="owner-nav"><a ${active === "create" ? 'aria-current="page"' : ""} href="/create">New secret</a><a ${active === "links" ? 'aria-current="page"' : ""} href="/create/links">My links</a></nav>`;
function shell(title: string, content: string, script?: string) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>${title} — F12 OTS</title><link rel="stylesheet" href="/ots.css">${script ? `<script src="${script}" defer></script>` : ""}</head><body><a class="skip" href="#main">Skip to content</a><header class="mast"><a class="brand" href="/">F12 OTS</a><span>One-time secret</span><span class="signal">● server-blind</span></header><main id="main">${content}</main>${footer}</body></html>`;
}

const revealContent = `<section id="reveal-view" class="task" hidden><p class="eyebrow">Incoming secret</p><h1>Reveal once</h1><p class="lede">A successful reveal permanently deletes the encrypted server copy.</p><div id="password-step" class="subpanel" hidden><label for="reveal-password">Separate password</label><input id="reveal-password" type="password" maxlength="256" autocomplete="current-password"><p class="fine-print">Get it from the sender through a different channel. F12 never receives it.</p></div><div id="reveal-ready"><button id="reveal-button" class="button" type="button">Reveal secret</button></div><div id="revealed" class="result" hidden><label for="revealed-secret">Secret</label><textarea id="revealed-secret" readonly></textarea><button id="copy-secret" class="button quiet" type="button">Copy</button></div><p id="reveal-status" class="message" role="status"></p></section>`;
const homeContent = `<section id="home-view" class="task"><p class="eyebrow">One-time secret</p><h1>Send a secret without storing plaintext</h1><p class="lede">Encryption and decryption happen in the browser. The encrypted payload can be opened once.</p><div class="home-actions"><a class="button" href="/create">Create a secret</a><a class="button quiet" href="/safety">How it works</a></div></section>`;
const homePage = shell("One Time Secret", homeContent + revealContent, "/home.js");

const createPage = shell("Create a secret", nav("create") + `<section class="task"><p class="eyebrow">New secret</p><h1>Create a one-time link</h1><p class="lede">The secret is encrypted in this browser. F12 stores only ciphertext.</p><form id="create-form"><label for="secret">Secret text</label><textarea id="secret" maxlength="12000" required autocomplete="off" spellcheck="false" autofocus></textarea><label for="expiry">Delete if unopened after</label><select id="expiry"><option value="900">15 minutes</option><option value="3600">1 hour</option><option value="21600" selected>6 hours</option><option value="86400">24 hours</option><option value="604800">7 days</option></select><label class="check-row"><input id="use-password" type="checkbox"><span>Require a separate password</span></label><div id="password-fields" class="subpanel" hidden><label for="create-password">Password</label><input id="create-password" type="password" minlength="12" maxlength="256" autocomplete="new-password"><label for="confirm-password">Confirm password</label><input id="confirm-password" type="password" minlength="12" maxlength="256" autocomplete="new-password"><p class="fine-print">At least 12 characters. Send it through another channel.</p></div><label class="acknowledgment"><input id="bearer-ack" type="checkbox" required><span>I understand the full link is sensitive and cannot be recovered later.</span></label><button class="button" type="submit">Create one-time link</button></form><div id="create-result" class="result" hidden><label for="share-url">One-time link</label><div class="copy"><input id="share-url" readonly><button id="copy-link" class="button" type="button">Copy</button></div><p class="fine-print">This is the only time the full link is shown. Send an optional password separately.</p></div><p id="create-status" class="message" role="status"></p></section>`, "/create.js");

const linksPage = shell("My links", nav("links") + `<section class="task owner-list"><p class="eyebrow">Owner workspace</p><h1>My links</h1><p class="lede">Status and timing only. Full links and secret material are never available here.</p><div id="links-summary" class="summary">Loading…</div><div id="links-list" class="link-list"></div><p id="links-status" class="message" role="status"></p></section>`, "/owner.js");

function detailPage(id: string) {
  return shell("Link details", nav("links") + `<section class="task owner-detail" data-secret-id="${id}"><p><a href="/create/links">← My links</a></p><h1>Link details</h1><p class="lede">Status metadata only. The secret and its link cannot be recovered.</p><div id="link-detail" class="detail-card">Loading…</div><div id="delete-panel" hidden><p class="notice"><strong>Delete permanently removes the encrypted payload.</strong> A status receipt remains for 24 hours.</p><button id="delete-link" class="button danger" type="button">Delete payload</button></div><p id="detail-status" class="message" role="status"></p></section>`, "/owner.js");
}

const policyCopy: Record<string, { title: string; body: string }> = {
  "/safety": { title: "Safe handling", body: `<p class="notice"><strong>The complete link is sensitive.</strong> Add a separate password when the delivery channel needs another layer, and send it through a different channel.</p><h2>Send safely</h2><ol><li>Verify <strong>ots.f12.biz</strong>, minimize content, and choose the shortest expiry.</li><li>Use a strong, unique password of at least 12 characters.</li><li>Do not paste the link or password into bots, AI chats, tickets, logs, repositories, or screenshots.</li></ol><h2>Limits</h2><p>A wrong password does not consume the secret. Password wrapping slows guessing but cannot make a weak password safe. There is no recovery after reveal, expiry, or deletion.</p>` },
  "/privacy": { title: "Privacy & security", body: `<p>AES-256-GCM encryption happens in the browser. Password-protected links use PBKDF2-HMAC-SHA-256 to wrap a random content key. Passwords and derived keys are never sent or stored.</p><h2>Owner history</h2><p>My links shows only a reference, status, timestamps, encrypted size, and password-protection flag. It never stores or displays a reusable full link, claim token, password, key, ciphertext, or IV.</p><h2>Retention</h2><p>Reveal, expiry, or owner deletion removes encrypted payload material. A safe metadata receipt remains for up to 24 hours and is then deleted.</p>` },
  "/terms": { title: "Beta terms", body: `<p class="notice">Obtain jurisdiction-specific legal review before a public trial.</p><h2>Use</h2><p>Use F12 OTS only for lawful, authorized secret exchange. You are responsible for content, recipients, delivery channels, passwords, and compliance.</p><h2>Prohibited</h2><p>Do not distribute malware, stolen credentials, unlawful material, or information you lack authority to share. Do not probe, disrupt, evade limits, or access another person's secret.</p><h2>Availability</h2><p>This owner-only beta has no promise of continuous availability, recovery, backup, or fitness for a particular purpose.</p>` },
};
function policyPage(path: string) {
  const policy = policyCopy[path];
  return policy ? shell(policy.title, `<article class="policy task"><p><a href="/">← Home</a></p><h1>${policy.title}</h1>${policy.body}</article>`) : null;
}

export { createPage, detailPage, homePage, linksPage, policyPage, styles };
